name: Deploy Web

on:
  push:
    paths:
       - .github/workflows/main.yml
      - main.tf
      - providers.tf
  workflow_dispatch: 
jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    name: 'Deploy Static Website'

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURECLIENTID }}
      ARM_CLIENT_SECRET: ${{ secrets.MYSECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
      ARM_TENANT_ID: ${{ secrets.TENANTID }}
      WORKING_DIR: ./staticwebsite # Oppdater til korrekt sti

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: List files in the working directory
        run: ls -alh ${{ env.WORKING_DIR }}

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
