name: Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - '**/*.tf'

jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    name: 'Deploy Static Website'

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURECLIENTID }}
      ARM_CLIENT_SECRET: ${{ secrets.MYSECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
      ARM_TENANT_ID: ${{ secrets.TENANTID }}
      WORKING_DIR: ./staticwebsite  # Juster om nødvendig

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: List repository files
        run: ls -alh

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
